In [5]:
import sqlite3
import sqlalchemy
import pandas
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func, inspect, desc
sqlite_file = 'data.sqlite'

In [15]:
import pandas as pd
import sqlite3
conn = sqlite3.connect("baseball.sqlite")
df = pd.read_sql_query("select * from final limit 5;", conn)
df

,,playerID,birthYear,birthCountry,birthCity,deathYear,deathCountry,deathCity,nameFirst,nameLast,...,continent_code,country_iso_code,country_name,city_name,registered_country_geoname_id,latitude,longitude,lat,lng,flags
0,0,aardsda01,1981.0,United States,Denver,,,,David,Aardsma,...,,US,United States,Denver,6252001.0,35.4837,-80.9898,39.7621,-104.8759,https://upload.wikimedia.org/wikipedia/en/a/a4...
1,1,aaronha01,1934.0,United States,Mobile,,,,Hank,Aaron,...,,US,United States,Mobile,6252001.0,30.5928,-88.1946,30.6783,-88.1162,https://upload.wikimedia.org/wikipedia/en/a/a4...
2,2,aaronto01,1939.0,United States,Mobile,1984.0,USA,Atlanta,Tommie,Aaron,...,,US,United States,Mobile,6252001.0,30.5928,-88.1946,30.6783,-88.1162,https://upload.wikimedia.org/wikipedia/en/a/a4...
3,3,aasedo01,1954.0,United States,Orange,,,,Don,Aase,...,,US,United States,Orange,6252001.0,30.0709,-93.8659,38.2486,-78.1127,https://upload.wikimedia.org/wikipedia/en/a/a4...
4,4,abadan01,1972.0,United States,Palm Beach,,,,Andy,Abad,...,,US,United States,Palm Beach,6252001.0,26.7206,-80.0388,26.6852,-80.0403,https://upload.wikimedia.org/wikipedia/en/a/a4...

In [11]:
mycur = conn.cursor() 
mycur.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;")
available_table=(mycur.fetchall())

In [12]:
available_table

[('Deploy1',)]