In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("fulldata.csv")
cities = pd.read_csv("GeoLiteCities.csv")
locations = pd.read_csv("GeoLitLocations.csv")

In [3]:
data = data.drop(columns = ['birthMonth', 'birthDay',
       'birthState', 'deathMonth', 'deathDay',
       'deathState',
       'nameGiven', 'weight', 'height', 'bats', 'throws', 'debut', 'finalGame',
       'retroID', 'bbrefID', 'Position', 'HoF'])

In [4]:
namer={"USA": "United States", "D.R.": "Domincan Republic", 'CAN': "Canada", "P.R.": "Puerto Rico", "V.I.": "U.S. Virgin Islands"}

In [5]:
data = data.replace({"birthCountry": namer})

In [6]:
data = data.dropna(subset=['birthCountry'])
data = data.dropna(subset=['birthCity'])

In [7]:
cities = cities.drop(columns=['network', 'represented_country_geoname_id', 'is_anonymous_proxy',
       'is_satellite_provider', 'postal_code', 'accuracy_radius'])

In [8]:
locations = locations.drop(columns=['locale_code', 'continent_name', 'subdivision_1_iso_code',
       'subdivision_1_name', 'subdivision_2_iso_code', 'subdivision_2_name',
       'time_zone', 'is_in_european_union', 'metro_code'])

In [9]:
locator = locations.merge(cities, on = "geoname_id", how = "right")

In [10]:
locator = locator.drop_duplicates(subset=['geoname_id'], keep='first')

In [11]:
data['Birthplace'] = data['birthCountry'] + " " + data['birthCity']

In [12]:
locator['Birthplace'] = locator['country_name'] + " " + locator['city_name']

In [13]:
final = data.merge(locator, on='Birthplace', how='left')

In [14]:
final

,playerID,birthYear,birthCountry,birthCity,deathYear,deathCountry,deathCity,nameFirst,nameLast,Birthplace,geoname_id,continent_code,country_iso_code,country_name,city_name,registered_country_geoname_id,latitude,longitude
0,aardsda01,1981.0,United States,Denver,NaN,NaN,NaN,David,Aardsma,United States Denver,4463523.0,NaN,US,United States,Denver,6252001.0,35.4837,-80.9898
1,aardsda01,1981.0,United States,Denver,NaN,NaN,NaN,David,Aardsma,United States Denver,4853799.0,NaN,US,United States,Denver,6252001.0,42.6731,-92.3417
2,aardsda01,1981.0,United States,Denver,NaN,NaN,NaN,David,Aardsma,United States Denver,5186794.0,NaN,US,United States,Denver,6252001.0,40.2297,-76.1157
3,aardsda01,1981.0,United States,Denver,NaN,NaN,NaN,David,Aardsma,United States Denver,5419384.0,NaN,US,United States,Denver,6252001.0,39.7318,-104.9669
4,aaronha01,1934.0,United States,Mobile,NaN,NaN,NaN,Hank,Aaron,United States Mobile,4076598.0,NaN,US,United States,Mobile,6252001.0,30.6605,-88.1618
5,aaronto01,1939.0,United States,Mobile,1984.0,USA,Atlanta,Tommie,Aaron,United States Mobile,4076598.0,NaN,US,United States,Mobile,6252001.0,30.6605,-88.1618
6,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,4716805.0,NaN,US,United States,Orange,6252001.0,30.0709,-93.8659
7,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,4777454.0,NaN,US,United States,Orange,6252001.0,38.2192,-78.0461
8,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,4840104.0,NaN,US,United States,Orange,6252001.0,41.2815,-73.0287
9,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,4946383.0,NaN,US,United States,Orange,6252001.0,42.6129,-72.2924
10,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,5102213.0,NaN,US,United States,Orange,6252001.0,40.7747,-74.2274
11,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,5379513.0,NaN,US,United States,Orange,6252001.0,33.7858,-117.8448
12,abadan01,1972.0,United States,Palm Beach,NaN,NaN,NaN,Andy,Abad,United States Palm Beach,4167505.0,NaN,US,United States,Palm Beach,6252001.0,26.7206,-80.0388
13,abadfe01,1985.0,Domincan Republic,La Romana,NaN,NaN,NaN,Fernando,Abad,Domincan Republic La Romana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,abadijo01,1850.0,United States,Philadelphia,1905.0,USA,Pemberton,John,Abadie,United States Philadelphia,4440906.0,NaN,US,United States,Philadelphia,6252001.0,32.7572,-89.1154
15,abadijo01,1850.0,United States,Philadelphia,1905.0,USA,Pemberton,John,Abadie,United States Philadelphia,4560349.0,NaN,US,United States,Philadelphia,2635167.0,39.9543,-75.1657
16,abadijo01,1850.0,United States,Philadelphia,1905.0,USA,Pemberton,John,Abadie,United States Philadelphia,4649014.0,NaN,US,United States,Philadelphia,6252001.0,35.6781,-84.4312
17,abadijo01,1850.0,United States,Philadelphia,1905.0,USA,Pemberton,John,Abadie,United States Philadelphia,5131095.0,NaN,US,United States,Philadelphia,6252001.0,44.1589,-75.7099
18,abbated01,1877.0,United States,Latrobe,1957.0,USA,Fort Lauderdale,Ed,Abbaticchio,United States Latrobe,5197227.0,NaN,US,United States,Latrobe,6252001.0,40.2917,-79.4054
19,abbeybe01,1869.0,United States,Essex,1962.0,USA,Colchester,Bert,Abbey,United States Essex,4354428.0,NaN,US,United States,Essex,6252001.0,39.3055,-76.4518
20,abbeybe01,1869.0,United States,Essex,1962.0,USA,Colchester,Bert,Abbey,United States Essex,4385785.0,NaN,US,United States,Essex,6252001.0,36.8109,-89.8366
21,abbeybe01,1869.0,United States,Essex,1962.0,USA,Colchester,Bert,Abbey,United States Essex,4834089.0,NaN,US,United States,Essex,6252001.0,41.3549,-72.3965
22,abbeybe01,1869.0,United States,Essex,1962.0,USA,Colchester,Bert,Abbey,United States Essex,4935946.0,NaN,US,United States,Essex,6252001.0,42.6286,-70.7828
23,abbeybe01,1869.0,United States,Essex,1962.0,USA,Colchester,Bert,Abbey,United States Essex,5116677.0,NaN,US,United States,Essex,6252001.0,44.2807,-73.3731
24,abbeych01,1866.0,United States,Falls City,1926.0,USA,San Francisco,Charlie,Abbey,United States Falls City,4690097.0,NaN,US,United States,Falls City,6252001.0,28.9814,-98.0156
25,abbotda01,1862.0,United States,Portage,1930.0,USA,Ottawa Lake,Dan,Abbott,United States Portage,4925006.0,NaN,US,United States,Portage,6252001.0,41.5681,-87.1749
26,abbotda01,1862.0,United States,Portage,1930.0,USA,Ottawa Lake,Dan,Abbott,United States Portage,5006250.0,NaN,US,United States,Portage,6252001.0,42.1938,-85.5639
27,abbotda01,1862.0,United States,Portage,1930.0,USA,Ottawa Lake,Dan,Abbott,United States Portage,5167278.0,NaN,US,United States,Portage,6252001.0,41.3127,-83.6143
28,abbotda01,1862.0,United States,Portage,1930.0,USA,Ottawa Lake,Dan,Abbott,United States Portage,5206961.0,NaN,US,United States,Portage,6252001.0,40.3724,-78.6328
29,abbotda01,1862.0,United States,Portage,1930.0,USA,Ottawa Lake,Dan,Abbott,United States Portage,5267785.0,NaN,US,United States,Portage,6252001.0,43.5501,-89.4714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65030,zobribe01,1981.0,United States,Eureka,NaN,NaN,NaN,Ben,Zobrist,United States Eureka,5503804.0,NaN,US,United States,Eureka,6252001.0,39.5897,-115.9943
65031,zobribe01,1981.0,United States,Eureka,NaN,NaN,NaN,Ben,Zobrist,United States Eureka,5563397.0,NaN,US,United States,Eureka,6252001.0,40.7977,-124.1565
65032,zoccope01,1977.0,United States,Bronx,NaN,NaN,NaN,Peter,Zoccolillo,United States Bronx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65033,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,4349594.0,NaN,US,United States,Brooklyn,6252001.0,39.2259,-76.6153
65034,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,4849448.0,NaN,US,United States,Brooklyn,6252001.0,41.7321,-92.4285
65035,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,4987064.0,NaN,US,United States,Brooklyn,6252001.0,42.1044,-84.2414
65036,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,5110302.0,NaN,US,United States,Brooklyn,6252001.0,40.6940,-73.9901
65037,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,5246849.0,NaN,US,United States,Brooklyn,6252001.0,42.8423,-89.3818
65038,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,5282922.0,NaN,US,United States,Brooklyn,6252001.0,41.7807,-71.9541
65039,zoskyed01,1968.0,United States,Whittier,NaN,NaN,NaN,Eddie,Zosky,United States Whittier,4498964.0,NaN,US,United States,Whittier,6252001.0,35.4469,-83.2872
65040,zoskyed01,1968.0,United States,Whittier,NaN,NaN,NaN,Eddie,Zosky,United States Whittier,5409059.0,NaN,US,United States,Whittier,6252001.0,33.9794,-118.0609
65041,zoskyed01,1968.0,United States,Whittier,NaN,NaN,NaN,Eddie,Zosky,United States Whittier,5878018.0,NaN,US,United States,Whittier,6252001.0,60.7734,-148.6839
65042,zuberbi01,1913.0,United States,Middle Amana,1982.0,USA,Cedar Rapids,Bill,Zuber,United States Middle Amana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65043,zuberjo01,1969.0,United States,Encino,NaN,NaN,NaN,Jon,Zuber,United States Encino,5346649.0,NaN,US,United States,Encino,6252001.0,34.1569,-118.4880
65044,zuberjo01,1969.0,United States,Encino,NaN,NaN,NaN,Jon,Zuber,United States Encino,5466839.0,NaN,US,United States,Encino,6252001.0,34.6512,-105.4617
65045,zuletju01,1975.0,Panama,Panama,NaN,NaN,NaN,Julio,Zuleta,Panama Panama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65046,zumayjo01,1984.0,United States,Chula Vista,NaN,NaN,NaN,Joel,Zumaya,United States Chula Vista,5336899.0,NaN,US,United States,Chula Vista,6252001.0,32.6387,-117.0801
65047,zuninmi01,1991.0,United States,Cape Coral,NaN,NaN,NaN,Mike,Zunino,United States Cape Coral,4149962.0,NaN,US,United States,Cape Coral,6252001.0,26.6292,-81.9680
65048,zupcibo01,1966.0,United States,Pittsburgh,NaN,NaN,NaN,Bob,Zupcic,United States Pittsburgh,5206379.0,NaN,US,United States,Pittsburgh,6252001.0,40.4688,-80.0872
65049,zupofr01,1939.0,United States,San Francisco,2005.0,USA,Burlingame,Frank,Zupo,United States San Francisco,5391959.0,NaN,US,United States,San Francisco,2017370.0,37.7751,-122.4193
65050,zuvelpa01,1958.0,United States,San Mateo,NaN,NaN,NaN,Paul,Zuvella,United States San Mateo,4171821.0,NaN,US,United States,San Mateo,6252001.0,29.5888,-81.5921
65051,zuvelpa01,1958.0,United States,San Mateo,NaN,NaN,NaN,Paul,Zuvella,United States San Mateo,5392423.0,NaN,US,United States,San Mateo,6252001.0,37.5549,-122.2708
65052,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,4259023.0,NaN,US,United States,Holland,6252001.0,38.2456,-87.0361
65053,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,4698254.0,NaN,US,United States,Holland,6252001.0,30.8800,-97.3857
65054,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,4860853.0,NaN,US,United States,Holland,6252001.0,42.4011,-92.7999
65055,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,4996248.0,NaN,US,United States,Holland,6252001.0,42.7686,-86.1170
65056,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,5099175.0,NaN,US,United States,Holland,6252001.0,40.5929,-75.1025
65057,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,5157759.0,NaN,US,United States,Holland,6252001.0,41.6226,-83.7257
65058,zwilldu01,1888.0,United States,St. Louis,1978.0,USA,La Crescenta,Dutch,Zwilling,United States St. Louis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65059,zychto01,1990.0,United States,Monee,NaN,NaN,NaN,Tony,Zych,United States Monee,4902498.0,NaN,US,United States,Monee,6252001.0,41.4191,-87.7748

In [15]:
final = final.dropna(subset=['latitude'])

In [16]:
final

,playerID,birthYear,birthCountry,birthCity,deathYear,deathCountry,deathCity,nameFirst,nameLast,Birthplace,geoname_id,continent_code,country_iso_code,country_name,city_name,registered_country_geoname_id,latitude,longitude
0,aardsda01,1981.0,United States,Denver,NaN,NaN,NaN,David,Aardsma,United States Denver,4463523.0,NaN,US,United States,Denver,6252001.0,35.4837,-80.9898
1,aardsda01,1981.0,United States,Denver,NaN,NaN,NaN,David,Aardsma,United States Denver,4853799.0,NaN,US,United States,Denver,6252001.0,42.6731,-92.3417
2,aardsda01,1981.0,United States,Denver,NaN,NaN,NaN,David,Aardsma,United States Denver,5186794.0,NaN,US,United States,Denver,6252001.0,40.2297,-76.1157
3,aardsda01,1981.0,United States,Denver,NaN,NaN,NaN,David,Aardsma,United States Denver,5419384.0,NaN,US,United States,Denver,6252001.0,39.7318,-104.9669
4,aaronha01,1934.0,United States,Mobile,NaN,NaN,NaN,Hank,Aaron,United States Mobile,4076598.0,NaN,US,United States,Mobile,6252001.0,30.6605,-88.1618
5,aaronto01,1939.0,United States,Mobile,1984.0,USA,Atlanta,Tommie,Aaron,United States Mobile,4076598.0,NaN,US,United States,Mobile,6252001.0,30.6605,-88.1618
6,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,4716805.0,NaN,US,United States,Orange,6252001.0,30.0709,-93.8659
7,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,4777454.0,NaN,US,United States,Orange,6252001.0,38.2192,-78.0461
8,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,4840104.0,NaN,US,United States,Orange,6252001.0,41.2815,-73.0287
9,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,4946383.0,NaN,US,United States,Orange,6252001.0,42.6129,-72.2924
10,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,5102213.0,NaN,US,United States,Orange,6252001.0,40.7747,-74.2274
11,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,5379513.0,NaN,US,United States,Orange,6252001.0,33.7858,-117.8448
12,abadan01,1972.0,United States,Palm Beach,NaN,NaN,NaN,Andy,Abad,United States Palm Beach,4167505.0,NaN,US,United States,Palm Beach,6252001.0,26.7206,-80.0388
14,abadijo01,1850.0,United States,Philadelphia,1905.0,USA,Pemberton,John,Abadie,United States Philadelphia,4440906.0,NaN,US,United States,Philadelphia,6252001.0,32.7572,-89.1154
15,abadijo01,1850.0,United States,Philadelphia,1905.0,USA,Pemberton,John,Abadie,United States Philadelphia,4560349.0,NaN,US,United States,Philadelphia,2635167.0,39.9543,-75.1657
16,abadijo01,1850.0,United States,Philadelphia,1905.0,USA,Pemberton,John,Abadie,United States Philadelphia,4649014.0,NaN,US,United States,Philadelphia,6252001.0,35.6781,-84.4312
17,abadijo01,1850.0,United States,Philadelphia,1905.0,USA,Pemberton,John,Abadie,United States Philadelphia,5131095.0,NaN,US,United States,Philadelphia,6252001.0,44.1589,-75.7099
18,abbated01,1877.0,United States,Latrobe,1957.0,USA,Fort Lauderdale,Ed,Abbaticchio,United States Latrobe,5197227.0,NaN,US,United States,Latrobe,6252001.0,40.2917,-79.4054
19,abbeybe01,1869.0,United States,Essex,1962.0,USA,Colchester,Bert,Abbey,United States Essex,4354428.0,NaN,US,United States,Essex,6252001.0,39.3055,-76.4518
20,abbeybe01,1869.0,United States,Essex,1962.0,USA,Colchester,Bert,Abbey,United States Essex,4385785.0,NaN,US,United States,Essex,6252001.0,36.8109,-89.8366
21,abbeybe01,1869.0,United States,Essex,1962.0,USA,Colchester,Bert,Abbey,United States Essex,4834089.0,NaN,US,United States,Essex,6252001.0,41.3549,-72.3965
22,abbeybe01,1869.0,United States,Essex,1962.0,USA,Colchester,Bert,Abbey,United States Essex,4935946.0,NaN,US,United States,Essex,6252001.0,42.6286,-70.7828
23,abbeybe01,1869.0,United States,Essex,1962.0,USA,Colchester,Bert,Abbey,United States Essex,5116677.0,NaN,US,United States,Essex,6252001.0,44.2807,-73.3731
24,abbeych01,1866.0,United States,Falls City,1926.0,USA,San Francisco,Charlie,Abbey,United States Falls City,4690097.0,NaN,US,United States,Falls City,6252001.0,28.9814,-98.0156
25,abbotda01,1862.0,United States,Portage,1930.0,USA,Ottawa Lake,Dan,Abbott,United States Portage,4925006.0,NaN,US,United States,Portage,6252001.0,41.5681,-87.1749
26,abbotda01,1862.0,United States,Portage,1930.0,USA,Ottawa Lake,Dan,Abbott,United States Portage,5006250.0,NaN,US,United States,Portage,6252001.0,42.1938,-85.5639
27,abbotda01,1862.0,United States,Portage,1930.0,USA,Ottawa Lake,Dan,Abbott,United States Portage,5167278.0,NaN,US,United States,Portage,6252001.0,41.3127,-83.6143
28,abbotda01,1862.0,United States,Portage,1930.0,USA,Ottawa Lake,Dan,Abbott,United States Portage,5206961.0,NaN,US,United States,Portage,6252001.0,40.3724,-78.6328
29,abbotda01,1862.0,United States,Portage,1930.0,USA,Ottawa Lake,Dan,Abbott,United States Portage,5267785.0,NaN,US,United States,Portage,6252001.0,43.5501,-89.4714
30,abbotfr01,1874.0,United States,Versailles,1935.0,USA,Los Angeles,Fred,Abbott,United States Versailles,4266266.0,NaN,US,United States,Versailles,6252001.0,39.0511,-85.2235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65026,zobribe01,1981.0,United States,Eureka,NaN,NaN,NaN,Ben,Zobrist,United States Eureka,4271159.0,NaN,US,United States,Eureka,6252001.0,37.8265,-96.2959
65027,zobribe01,1981.0,United States,Eureka,NaN,NaN,NaN,Ben,Zobrist,United States Eureka,4385835.0,NaN,US,United States,Eureka,6252001.0,38.5128,-90.6306
65028,zobribe01,1981.0,United States,Eureka,NaN,NaN,NaN,Ben,Zobrist,United States Eureka,4891310.0,NaN,US,United States,Eureka,6252001.0,40.7152,-89.2706
65029,zobribe01,1981.0,United States,Eureka,NaN,NaN,NaN,Ben,Zobrist,United States Eureka,5227665.0,NaN,US,United States,Eureka,6252001.0,45.7707,-99.3308
65030,zobribe01,1981.0,United States,Eureka,NaN,NaN,NaN,Ben,Zobrist,United States Eureka,5503804.0,NaN,US,United States,Eureka,6252001.0,39.5897,-115.9943
65031,zobribe01,1981.0,United States,Eureka,NaN,NaN,NaN,Ben,Zobrist,United States Eureka,5563397.0,NaN,US,United States,Eureka,6252001.0,40.7977,-124.1565
65033,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,4349594.0,NaN,US,United States,Brooklyn,6252001.0,39.2259,-76.6153
65034,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,4849448.0,NaN,US,United States,Brooklyn,6252001.0,41.7321,-92.4285
65035,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,4987064.0,NaN,US,United States,Brooklyn,6252001.0,42.1044,-84.2414
65036,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,5110302.0,NaN,US,United States,Brooklyn,6252001.0,40.6940,-73.9901
65037,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,5246849.0,NaN,US,United States,Brooklyn,6252001.0,42.8423,-89.3818
65038,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,5282922.0,NaN,US,United States,Brooklyn,6252001.0,41.7807,-71.9541
65039,zoskyed01,1968.0,United States,Whittier,NaN,NaN,NaN,Eddie,Zosky,United States Whittier,4498964.0,NaN,US,United States,Whittier,6252001.0,35.4469,-83.2872
65040,zoskyed01,1968.0,United States,Whittier,NaN,NaN,NaN,Eddie,Zosky,United States Whittier,5409059.0,NaN,US,United States,Whittier,6252001.0,33.9794,-118.0609
65041,zoskyed01,1968.0,United States,Whittier,NaN,NaN,NaN,Eddie,Zosky,United States Whittier,5878018.0,NaN,US,United States,Whittier,6252001.0,60.7734,-148.6839
65043,zuberjo01,1969.0,United States,Encino,NaN,NaN,NaN,Jon,Zuber,United States Encino,5346649.0,NaN,US,United States,Encino,6252001.0,34.1569,-118.4880
65044,zuberjo01,1969.0,United States,Encino,NaN,NaN,NaN,Jon,Zuber,United States Encino,5466839.0,NaN,US,United States,Encino,6252001.0,34.6512,-105.4617
65046,zumayjo01,1984.0,United States,Chula Vista,NaN,NaN,NaN,Joel,Zumaya,United States Chula Vista,5336899.0,NaN,US,United States,Chula Vista,6252001.0,32.6387,-117.0801
65047,zuninmi01,1991.0,United States,Cape Coral,NaN,NaN,NaN,Mike,Zunino,United States Cape Coral,4149962.0,NaN,US,United States,Cape Coral,6252001.0,26.6292,-81.9680
65048,zupcibo01,1966.0,United States,Pittsburgh,NaN,NaN,NaN,Bob,Zupcic,United States Pittsburgh,5206379.0,NaN,US,United States,Pittsburgh,6252001.0,40.4688,-80.0872
65049,zupofr01,1939.0,United States,San Francisco,2005.0,USA,Burlingame,Frank,Zupo,United States San Francisco,5391959.0,NaN,US,United States,San Francisco,2017370.0,37.7751,-122.4193
65050,zuvelpa01,1958.0,United States,San Mateo,NaN,NaN,NaN,Paul,Zuvella,United States San Mateo,4171821.0,NaN,US,United States,San Mateo,6252001.0,29.5888,-81.5921
65051,zuvelpa01,1958.0,United States,San Mateo,NaN,NaN,NaN,Paul,Zuvella,United States San Mateo,5392423.0,NaN,US,United States,San Mateo,6252001.0,37.5549,-122.2708
65052,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,4259023.0,NaN,US,United States,Holland,6252001.0,38.2456,-87.0361
65053,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,4698254.0,NaN,US,United States,Holland,6252001.0,30.8800,-97.3857
65054,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,4860853.0,NaN,US,United States,Holland,6252001.0,42.4011,-92.7999
65055,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,4996248.0,NaN,US,United States,Holland,6252001.0,42.7686,-86.1170
65056,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,5099175.0,NaN,US,United States,Holland,6252001.0,40.5929,-75.1025
65057,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,5157759.0,NaN,US,United States,Holland,6252001.0,41.6226,-83.7257
65059,zychto01,1990.0,United States,Monee,NaN,NaN,NaN,Tony,Zych,United States Monee,4902498.0,NaN,US,United States,Monee,6252001.0,41.4191,-87.7748

In [17]:
final= final.drop_duplicates(subset=['playerID'], keep='first')
final

,playerID,birthYear,birthCountry,birthCity,deathYear,deathCountry,deathCity,nameFirst,nameLast,Birthplace,geoname_id,continent_code,country_iso_code,country_name,city_name,registered_country_geoname_id,latitude,longitude
0,aardsda01,1981.0,United States,Denver,NaN,NaN,NaN,David,Aardsma,United States Denver,4463523.0,NaN,US,United States,Denver,6252001.0,35.4837,-80.9898
4,aaronha01,1934.0,United States,Mobile,NaN,NaN,NaN,Hank,Aaron,United States Mobile,4076598.0,NaN,US,United States,Mobile,6252001.0,30.6605,-88.1618
5,aaronto01,1939.0,United States,Mobile,1984.0,USA,Atlanta,Tommie,Aaron,United States Mobile,4076598.0,NaN,US,United States,Mobile,6252001.0,30.6605,-88.1618
6,aasedo01,1954.0,United States,Orange,NaN,NaN,NaN,Don,Aase,United States Orange,4716805.0,NaN,US,United States,Orange,6252001.0,30.0709,-93.8659
12,abadan01,1972.0,United States,Palm Beach,NaN,NaN,NaN,Andy,Abad,United States Palm Beach,4167505.0,NaN,US,United States,Palm Beach,6252001.0,26.7206,-80.0388
14,abadijo01,1850.0,United States,Philadelphia,1905.0,USA,Pemberton,John,Abadie,United States Philadelphia,4440906.0,NaN,US,United States,Philadelphia,6252001.0,32.7572,-89.1154
18,abbated01,1877.0,United States,Latrobe,1957.0,USA,Fort Lauderdale,Ed,Abbaticchio,United States Latrobe,5197227.0,NaN,US,United States,Latrobe,6252001.0,40.2917,-79.4054
19,abbeybe01,1869.0,United States,Essex,1962.0,USA,Colchester,Bert,Abbey,United States Essex,4354428.0,NaN,US,United States,Essex,6252001.0,39.3055,-76.4518
24,abbeych01,1866.0,United States,Falls City,1926.0,USA,San Francisco,Charlie,Abbey,United States Falls City,4690097.0,NaN,US,United States,Falls City,6252001.0,28.9814,-98.0156
25,abbotda01,1862.0,United States,Portage,1930.0,USA,Ottawa Lake,Dan,Abbott,United States Portage,4925006.0,NaN,US,United States,Portage,6252001.0,41.5681,-87.1749
30,abbotfr01,1874.0,United States,Versailles,1935.0,USA,Los Angeles,Fred,Abbott,United States Versailles,4266266.0,NaN,US,United States,Versailles,6252001.0,39.0511,-85.2235
34,abbotgl01,1951.0,United States,Little Rock,NaN,NaN,NaN,Glenn,Abbott,United States Little Rock,4119403.0,NaN,US,United States,Little Rock,6252001.0,34.6725,-92.3529
35,abbotje01,1972.0,United States,Atlanta,NaN,NaN,NaN,Jeff,Abbott,United States Atlanta,4180439.0,NaN,US,United States,Atlanta,6252001.0,33.9707,-84.3247
43,abbotji01,1967.0,United States,Flint,NaN,NaN,NaN,Jim,Abbott,United States Flint,4691498.0,NaN,US,United States,Flint,6252001.0,32.2079,-95.3948
45,abbotku01,1969.0,United States,Zanesville,NaN,NaN,NaN,Kurt,Abbott,United States Zanesville,4528923.0,NaN,US,United States,Zanesville,6252001.0,39.9275,-82.0032
47,abbotky01,1968.0,United States,Newburyport,NaN,NaN,NaN,Kyle,Abbott,United States Newburyport,4945256.0,NaN,US,United States,Newburyport,2017370.0,42.8133,-70.8814
49,abbotpa01,1967.0,United States,Van Nuys,NaN,NaN,NaN,Paul,Abbott,United States Van Nuys,5405693.0,NaN,US,United States,Van Nuys,6252001.0,34.1794,-118.4313
50,aberal01,1927.0,United States,Cleveland,1993.0,USA,Garfield Heights,Al,Aber,United States Cleveland,4055815.0,NaN,US,United States,Cleveland,6252001.0,33.9778,-86.5598
65,abercre01,1980.0,United States,Columbus,NaN,NaN,NaN,Reggie,Abercrombie,United States Columbus,4188985.0,NaN,US,United States,Columbus,6252001.0,32.4730,-84.9795
76,abernbi01,1929.0,United States,Torrance,2006.0,USA,Yucaipa,Bill,Abernathie,United States Torrance,5403022.0,NaN,US,United States,Torrance,6252001.0,33.8104,-118.3531
77,abernbr01,1977.0,United States,Atlanta,NaN,NaN,NaN,Brent,Abernathy,United States Atlanta,4180439.0,NaN,US,United States,Atlanta,6252001.0,33.9707,-84.3247
86,abernte02,1933.0,United States,Stanley,2004.0,USA,Gastonia,Ted,Abernathy,United States Stanley,4493226.0,NaN,US,United States,Stanley,6252001.0,35.3516,-81.0959
93,abernwo01,1915.0,United States,Forest City,1994.0,USA,Louisville,Woody,Abernathy,United States Forest City,4466720.0,NaN,US,United States,Forest City,6252001.0,35.3250,-81.8460
95,aberscl01,1921.0,United States,Chicago,1973.0,USA,Vallejo,Cliff,Aberson,United States Chicago,4887398.0,NaN,US,United States,Chicago,6252001.0,41.8777,-87.6376
96,ablesha01,1883.0,United States,Terrell,1951.0,USA,San Antonio,Harry,Ables,United States Terrell,4736028.0,NaN,US,United States,Terrell,6252001.0,32.7515,-96.2831
97,abnersh01,1966.0,United States,Hamilton,NaN,NaN,NaN,Shawn,Abner,United States Hamilton,4065965.0,NaN,US,United States,Hamilton,6252001.0,34.1534,-88.0085
108,abramca01,1924.0,United States,Philadelphia,1997.0,USA,Fort Lauderdale,Cal,Abrams,United States Philadelphia,4440906.0,NaN,US,United States,Philadelphia,6252001.0,32.7572,-89.1154
112,abramge01,1899.0,United States,Seattle,1986.0,USA,Clearwater,George,Abrams,United States Seattle,5809844.0,NaN,US,United States,Seattle,3077311.0,47.4902,-122.3004
113,abregjo01,1962.0,United States,Corpus Christi,NaN,NaN,NaN,Johnny,Abrego,United States Corpus Christi,4683416.0,NaN,US,United States,Corpus Christi,6252001.0,27.7262,-97.4078
115,abreujo01,1913.0,United States,Oakland,1993.0,USA,Hayward,Joe,Abreu,United States Oakland,4166628.0,NaN,US,United States,Oakland,6252001.0,28.5547,-81.6322
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64946,zimmehe01,1887.0,United States,New York,1969.0,USA,New York,Heinie,Zimmerman,United States New York,5128581.0,NaN,US,United States,New York,798549.0,40.7157,-74.0000
64947,zimmeje01,1934.0,United States,Omaha,1998.0,USA,Neskowin,Jerry,Zimmerman,United States Omaha,4124911.0,NaN,US,United States,Omaha,6252001.0,36.4612,-93.1888
64949,zimmeje02,1972.0,Canada,Kelowna,NaN,NaN,NaN,Jeff,Zimmerman,Canada Kelowna,5990579.0,NaN,CA,Canada,Kelowna,6251999.0,50.0221,-119.4054
64950,zimmejo01,1975.0,Canada,Kelowna,NaN,NaN,NaN,Jordan,Zimmerman,Canada Kelowna,5990579.0,NaN,CA,Canada,Kelowna,6251999.0,50.0221,-119.4054
64951,zimmejo02,1986.0,United States,Auburndale,NaN,NaN,NaN,Jordan,Zimmermann,United States Auburndale,4146389.0,NaN,US,United States,Auburndale,6252001.0,28.0699,-81.8107
64953,zimmero01,1913.0,United States,Pine Grove,1991.0,USA,Pine Grove,Roy,Zimmerman,United States Pine Grove,5206038.0,NaN,US,United States,Pine Grove,6252001.0,40.5671,-76.3269
64955,zimmery01,1984.0,United States,Washington,NaN,NaN,NaN,Ryan,Zimmerman,United States Washington,4140963.0,NaN,US,United States,Washington,6252001.0,38.9371,-76.9928
64974,zinkch01,1979.0,United States,Carmichael,NaN,NaN,NaN,Charlie,Zink,United States Carmichael,5334336.0,NaN,US,United States,Carmichael,6252001.0,38.6283,-121.3307
64975,zinkwa01,1898.0,United States,Pittsfield,1964.0,USA,Quincy,Walter,Zink,United States Pittsfield,4247060.0,NaN,US,United States,Pittsfield,6252001.0,39.6013,-90.8073
64979,zinnfr01,1865.0,United States,Phoenixville,1936.0,USA,Philadelphia,Frank,Zinn,United States Phoenixville,5205849.0,NaN,US,United States,Phoenixville,6252001.0,40.1262,-75.5268
64980,zinngu01,1887.0,United States,Holbrook,1949.0,USA,Park,Guy,Zinn,United States Holbrook,4939637.0,NaN,US,United States,Holbrook,6252001.0,42.1464,-71.0083
64984,zinnji01,1895.0,United States,Benton,1991.0,USA,Memphis,Jimmy,Zinn,United States Benton,4101241.0,NaN,US,United States,Benton,6252001.0,34.6054,-92.6255
64992,zinsebi01,1918.0,United States,Astoria,1993.0,USA,Englewood,Bill,Zinser,United States Astoria,4883749.0,NaN,US,United States,Astoria,6252001.0,40.2311,-90.3443
64995,zinteal01,1968.0,United States,El Paso,NaN,NaN,NaN,Alan,Zinter,United States El Paso,4890813.0,NaN,US,United States,El Paso,6252001.0,40.7389,-89.0120
64997,zipfebu01,1938.0,United States,Belleville,NaN,NaN,NaN,Bud,Zipfel,United States Belleville,4233813.0,NaN,US,United States,Belleville,6252001.0,38.5423,-89.9588
65003,ziskri01,1949.0,United States,Brooklyn,NaN,NaN,NaN,Richie,Zisk,United States Brooklyn,4349594.0,NaN,US,United States,Brooklyn,6252001.0,39.2259,-76.6153
65009,zitoba01,1978.0,United States,Las Vegas,NaN,NaN,NaN,Barry,Zito,United States Las Vegas,5475433.0,NaN,US,United States,Las Vegas,6252001.0,35.5949,-105.2272
65011,zitzmbi01,1895.0,United States,Long Island City,1985.0,USA,Passaic,Billy,Zitzmann,United States Long Island City,5125125.0,NaN,US,United States,Long Island City,6252001.0,40.7429,-73.9392
65012,zmiched01,1884.0,United States,Cleveland,1950.0,USA,Cleveland,Ed,Zmich,United States Cleveland,4055815.0,NaN,US,United States,Cleveland,6252001.0,33.9778,-86.5598
65026,zobribe01,1981.0,United States,Eureka,NaN,NaN,NaN,Ben,Zobrist,United States Eureka,4271159.0,NaN,US,United States,Eureka,6252001.0,37.8265,-96.2959
65033,zoldasa01,1918.0,United States,Brooklyn,1966.0,USA,New Hyde Park,Sam,Zoldak,United States Brooklyn,4349594.0,NaN,US,United States,Brooklyn,6252001.0,39.2259,-76.6153
65039,zoskyed01,1968.0,United States,Whittier,NaN,NaN,NaN,Eddie,Zosky,United States Whittier,4498964.0,NaN,US,United States,Whittier,6252001.0,35.4469,-83.2872
65043,zuberjo01,1969.0,United States,Encino,NaN,NaN,NaN,Jon,Zuber,United States Encino,5346649.0,NaN,US,United States,Encino,6252001.0,34.1569,-118.4880
65046,zumayjo01,1984.0,United States,Chula Vista,NaN,NaN,NaN,Joel,Zumaya,United States Chula Vista,5336899.0,NaN,US,United States,Chula Vista,6252001.0,32.6387,-117.0801
65047,zuninmi01,1991.0,United States,Cape Coral,NaN,NaN,NaN,Mike,Zunino,United States Cape Coral,4149962.0,NaN,US,United States,Cape Coral,6252001.0,26.6292,-81.9680
65048,zupcibo01,1966.0,United States,Pittsburgh,NaN,NaN,NaN,Bob,Zupcic,United States Pittsburgh,5206379.0,NaN,US,United States,Pittsburgh,6252001.0,40.4688,-80.0872
65049,zupofr01,1939.0,United States,San Francisco,2005.0,USA,Burlingame,Frank,Zupo,United States San Francisco,5391959.0,NaN,US,United States,San Francisco,2017370.0,37.7751,-122.4193
65050,zuvelpa01,1958.0,United States,San Mateo,NaN,NaN,NaN,Paul,Zuvella,United States San Mateo,4171821.0,NaN,US,United States,San Mateo,6252001.0,29.5888,-81.5921
65052,zuverge01,1924.0,United States,Holland,2014.0,USA,Tempe,George,Zuverink,United States Holland,4259023.0,NaN,US,United States,Holland,6252001.0,38.2456,-87.0361
65059,zychto01,1990.0,United States,Monee,NaN,NaN,NaN,Tony,Zych,United States Monee,4902498.0,NaN,US,United States,Monee,6252001.0,41.4191,-87.7748

In [18]:
final.to_csv("final.csv")